# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
pt:
  languageCode: pt
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-US
  contentDir: content/en
  title: Chinese website title...
  params:
    description: Site description in English...
  menu:
    main:
      - name: Biography
        url: /
        weight: 10
      - name: Publications
        url: /#papers
        weight: 11
      - name: Talks
        url: /#talks
        weight: 12
      - name: News
        url: /#news
        weight: 13
      - name: Experience
        url: experience/
        weight: 20
      - name: Projects
        url: projects/
        weight: 30
      - name: Tutorials
        url: teaching/
        weight: 40
